services:
  app:
    build:
      context: ./backend
      dockerfile: ../docker/php/Dockerfile
    container_name: laravel_app
    volumes:
      - ./backend:/var/www/html
      - storage_data:/var/www/html/storage
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_DATABASE=compasia
      - DB_USERNAME=root
      - DB_PASSWORD=root
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=compasia
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx_server
    ports:
      - "80:80"
    volumes:
      - ./backend:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network

  queue_worker:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: queue_worker
    restart: always
    command: >
          sh -c "chown -R www-data:www-data /var/www/html/storage /var/www/html/bootstrap/cache &&
           php artisan queue:work --sleep=3 --tries=3"
    volumes:
      - ./backend:/var/www/html
      - storage_data:/var/www/html/storage
    depends_on:
      - db
      - app
    networks:
      - app-network
  
  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/vue/Dockerfile
    container_name: vue_app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - app

networks:
  app-network:

volumes:
  mysql_data:
  storage_data: